language: haskell

install:
    - sudo apt-get update
    - sudo apt-get install libzookeeper-mt-dev zookeeperd
    - sleep 10
    - /usr/share/zookeeper/bin/zkCli.sh create /persistent null
    - cabal update
    - cabal install -j hspec cabal-meta cabal-src
    - cabal-meta install -j --only-dep --force-reinstalls
    - cabal-meta install -j

script:
    - mega-sdist --test
    - cd persistent-test
    - cabal install -j --only-dep  --enable-tests --force-reinstalls
    - "cabal configure -fmysql --enable-tests      && cabal test"
    - "cabal configure -fpostgresql --enable-tests && cabal test"
    - "cabal configure -fmongodb --enable-tests    && cabal test"
    - "cabal configure -fzookeeper --enable-tests  && cabal test"

addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database persistent;' -U postgres
  - mysql -e 'create database persistent;'

services:
    - mysql
    - mongodb
    - zookeeper
